### ISSUE TITLE
Syntax for for-loop

### ISSUE THREAD

**Issue by robcodonnell** [robcodonnell/robodonnell.ca#1]
@thomasjbradley If you have time would you mind helping me out with something? Im trying to write a for loop that would generate a feed of my portfolio pieces in my "work" page, using jekyll data files. 

I have my portfolio piece's data as .yml files, and I've been able to get the data from these files to generate the pages for each piece, but I can't seem to figure out how to get the data from all the pieces into one "work" page. I'd really appreciate it if you have time to take a look, I think it's just the syntax I'm having trouble with.

The page I'm trying to write this for loop on is work.html

Thanks

**Comment by thomasjbradley** [comment]
It's a little weird but here's the solution that you'll need:

```
{% for data in site.data.pieces %}
  {% for item in data %}
    {{item.piece.title}}
    <!-- All your HTML for each piece would go in here -->
  {% endfor %}
{% endfor %}
```

The outer loop moves through all the files in the `pieces` folder. Each file goes into `data`. Then the inner loop moves through all the “pieces” in each file (but there's only one).

**Comment by ericadamski** [comment]
@robcodonnel you won't be able to have a single loop to generate your multiple pages. But we can look at a different solution in class Monday :)

**Comment by robcodonnell** [comment]
@ericadamski @thomasjbradley thanks for getting back to me, the loop inside the loop works! But for some reason it outputs an empty chunk of code for each piece, is there an easy fix for this? I'll include screenshots of my code and what it looks like when output.
<img width="653" alt="screen shot 2016-11-13 at 2 05 04 pm" src="https://cloud.githubusercontent.com/assets/10464622/20248057/37882714-a9aa-11e6-94f1-9890c5e6e55e.png">
<img width="340" alt="screen shot 2016-11-13 at 2 02 23 pm" src="https://cloud.githubusercontent.com/assets/10464622/20248039/f5905462-a9a9-11e6-98b8-b7be113a16cd.png">

**Comment by ericadamski** [comment]
@robcodonnell I looks like you may have a bit of your `pieces.yml` that doesn't have exactly the same entries as the others. For example, if you have some yaml that looks like

```yaml
- title: "This is the Title"
  image: "img/the-image.png"

- image: "img/the-other-image.png
```

then all yaml bits of info must have a title and an image, so the second section might output some empty sections.
